### PR TITLE
Removed errors about threads not running in main

### PR DESCRIPTION
**Pull request by flynnguy**
So I found which threads it was complaining about and moved them from **init** into main() and now I don't get any errors. Also my segfault I mentioned before was my error when putting the app into a virtualenv and using the wrong python version, I fixed it by manually specifying the python version when creating the virtualenv.

So now it all seems to work so I just have to wait for my Laser Ammo to arrive in the mail! Thanks.

### CODE REVIEW

**Comment by phrack** [comment]
Keep em coming! I am not going to look at this until I finish releasing 1.3 (should be within the next hour) because master has been thoroughly tested by a couple people and is ready to go. I'd love to see you get ShootOFF stable on Mac and create a Pyinstaller package for Mac: https://github.com/phrack/ShootOFF/wiki/Making-a-ShootOFF-Package

**Comment by flynnguy** [comment]
Awesome, I'll take a look at making a mac package.

**Comment by phrack** [comment]
Do you have a timeline for trying to get a Mac package working? If it's in the very short term (next few days) and you succeed*, I'll rush this pull request through like your other one, otherwise I'll start planning for 1.4 and will merge it as part of that release.

*Not trying to be snarky, just that several people have offered to make a Mac package and no one has delivered yet. I am only aware of one honest attempt, but that individual didn't know how to debug a seg fault and never progressed past that.

**Comment by flynnguy** [comment]
Well I made an initial attempt and was unsuccessful. I will make more attempts but I would say don't wait.

**Comment by phrack** [comment]
I am closing this request for now because it appears to be dead. It's likely the request needs to pull multiple commits before being accepted as well.

Thanks for taking a look at this flynnguy. Shoot a message at me if I am wrong.

**Pull request closed without merging**
